function dyn_sys = system_function(x_1,x_2,xd_1,xd_2)
%SYSTEM_FUNCTION
%    DYN_SYS = SYSTEM_FUNCTION(X_1,X_2,XD_1,XD_2)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    02-Sep-2017 10:03:28

t2 = x_1.^2;
dyn_sys = [xd_1;xd_2;x_1.*-2.0+x_2-xd_1.*(3.0./5.0e1)+xd_2.*(3.0./1.0e2)-t2.*x_1.*(1.0./2.0);x_1-x_2.*2.0+xd_1.*(3.0./1.0e2)-xd_2.*(3.0./5.0e1)];
